apiVersion: v1
kind: Service
metadata:
  name: chainshield
  namespace: supply-chain-demo
spec:
  selector:
    app.kubernetes.io/name: chainshield
  ports:
    - name: http
      port: 80
      targetPort: http
